### ISSUE TITLE
Can we make auto-generated set_input method take `&self` instead of `&mut self`

### ISSUE THREAD

**Issue by nooberfsh** [salsa-rs/salsa#299]
Currently I need to wrap  my `DB`  inside some lock in a multi-threaded program which is a little inconvenient.
I found `set_xxx` method will call `InputQueryStorageOps<Q>::set` which only need `&self`, so can we make auto-generated set_input method just take `&self` ?

**Comment by KenDJohnson** [comment]
The DB uses internal locks, which is why the `InputQueryStorageOps<Q>::set` method is able to take `&self`, but requiring `&mut self` is an important part of the invariants of salsa's revision tracking. Each `set_*` call will create a new revision. Requiring `&mut self` ensures that only one thread can call a `set_*` method at once meaning there is always a "current revision" that is the one true revision.

There are some notes on that [here](https://hackmd.io/6x9f6mavTRS2imfG96tP5A#tangent-revisions) along with more explanation from @nikomatsakis in this [walkthrough](https://youtu.be/vrnNvAAoQFk?t=1384).

As for wrapping the DB to use across threads, the typical pattern - what I use, and what rust-analyzer does - is to have one thread that owns the DB, and is the only thread that will call the `set_*` methods. Then you create a [snapshot](https://docs.rs/salsa/latest/salsa/trait.ParallelDatabase.html#method.snapshot) ([example](https://github.com/rust-lang/rust-analyzer/blob/838cc9d3cc4de0abb52263a1fa2e9a6f0191a151/crates/ide_db/src/lib.rs#L150) impl from rust-analyzer) which is `Send + Sync` and can be passed around and queried by other threads.

**Comment by nikomatsakis** [comment]
The idea of "single mutator, multiple query threads" is pretty baked into salsa at this point, and I don't think we will change it. (In fact, I'd like to go further, eventually, and have salsa deploy its own thread pools and things). I think you'll just have to keep using a lock!  Sorry.
