### ISSUE TITLE
Automatically derive `DebugInDb` for salsa structs

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#317]
When you create a salsa struct (tracked/input/interned), we should automatically implement both `Debug` and `DebugInDb`.

For tracked/input structs in particular, the identity of the struct is important, so it is important to include not only the value of the fields but also the value of `self.0` (i.e., its numeric identity).

**Comment by agluszak** [comment]
Do you mean `DebugWithDb` (https://salsa-rs.github.io/salsa/tutorial/debug.html)? I'd like to implement that :)

**Comment by nikomatsakis** [comment]
@agluszak Yes! I think this issue is pretty important. Let me leave a few details -- or maybe there's a dup, I feel like I did write some stuff already...

**Comment by nikomatsakis** [comment]
I edited the OP a bit to clarify the intent. Let me add a few brief mentoring instructions, @agluszak. 

As an example of what I would like to auto-generate, you can see the implementations in the tutorial:

https://github.com/salsa-rs/salsa/blob/8dfc578edc2c62cef84c49da247dc199b50740ae/calc-example/calc/src/ir.rs#L75-L83

I think I would do this by modifying [`salsa_struct.rs` in the macro crate](https://github.com/salsa-rs/salsa/blob/8dfc578edc2c62cef84c49da247dc199b50740ae/components/salsa-2022-macros/src/salsa_struct.rs) --- this contains the common code shared by all the different structs. I would add some method like `debug_in_db_impl` that returns a `syn::ItemImpl` or maybe just a tokenstream (up to you). Then you have to modify the individual struct files to invoke it and include it in their output.

A good example to follow is the `as_id_impl` helper method. It is defined here, in `salsa_struct.rs`:

https://github.com/salsa-rs/salsa/blob/8dfc578edc2c62cef84c49da247dc199b50740ae/components/salsa-2022-macros/src/salsa_struct.rs#L279-L294

...and then invoked by each kind of struct and included in their final output. Here is the code from `tracked_struct.rs`:

https://github.com/salsa-rs/salsa/blob/8dfc578edc2c62cef84c49da247dc199b50740ae/components/salsa-2022-macros/src/tracked_struct.rs#L44-L54

Input structs do the same general thing:

https://github.com/salsa-rs/salsa/blob/8dfc578edc2c62cef84c49da247dc199b50740ae/components/salsa-2022-macros/src/input.rs#L39-L50

As do interned structs:

https://github.com/salsa-rs/salsa/blob/8dfc578edc2c62cef84c49da247dc199b50740ae/components/salsa-2022-macros/src/interned.rs#L39-L50

**Comment by agluszak** [comment]
So I'm wondering how to tackle this part: `When printing the value of a field, use .field(&a.debug(db)) for fields that are themselves interned or entities, and use .field(&a) for fields that just implement the ordinary Debug trait.`.

Is there a way to check from inside a whether a field implements `Debug`? I was trying to get around this by always calling `.debug(db)` and implementing `DebugWithDb` for stdlib types which were used in the tests, but sooner or later someone will run into a type which isn't owned by them and they won't be able to provide `DebugWithDb` impl for it because of orphan rules. So maybe instead of deriving `DebugWithDb` as a part of `#[tracked], #[interned] and #[input]` we should add a separate, optional macro just for that? This way it will still be possible to write an impl manually.

**Comment by crlf0710** [comment]
> Is there a way to check from inside a macro whether a field implements Debug (other than specialization)?

@agluszak Yes! Since this is not generic code, real specialization is not needed at all! You can exercise the tricks in https://docs.rs/has_impl/ for this sort of things, i.e. (The resolution priorities of inherent and trait impl can be used to differ "implemented a trait" and "didn't implement a trait")

**Comment by agluszak** [comment]
@crlf0710 Thanks! I think I figured it out, but also found a surprising thing along the way: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=da107e619bd142c81f7bad595d5024b8

**Comment by nikomatsakis** [comment]
@agluszak oh, right! I forgot about that.

I had actually planned to use an attribute on the fields, I think, but if we can find something more clever, maybe that's worth the trouble.

**Comment by nikomatsakis** [comment]
I guess using the "has-impl"-style trick is a good idea.

**Comment by agluszak** [comment]
> I had actually planned to use an attribute on the fields, I think, but if we can find something more clever, maybe that's worth the trouble.

@nikomatsakis an attribute on the fields for what specifically?

I'm getting closer and closer to a working prototype, I'll be creating a draft PR soon :)
