### ISSUE TITLE
`debug` method of `DependencyIndex` should be more human readable.

### ISSUE THREAD

**Issue by XFFXFF** [salsa-rs/salsa#340]
https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022/src/key.rs#L36-L38  
Currently, we just return `self` in `debug` method of `DependecyIndex`, so when call `debug`, will get something like  
```rust
DependencyIndex { ingredient_index: IngredientIndex(8), key_index: Some(Id { value: 1 }) }
```
which is not human friendly. Instead of the index, we can output information about the raw values of the ingradient and key. An expected output could be `func_name(arg_value)` for a tracked function.

**Comment by nikomatsakis** [comment]
The old code did a better job here. Let me try to write up some mentoring instructions. First let me dig up how the old code worked.

### Old code

You would invoke [`debug`](https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/src/lib.rs#L403-L410) on a `DatabaseKeyIndex` to get back a custom struct (Salsa 2022 has a [standard trait](https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022/src/debug.rs#L7) for this). The `Debug` impl for this custom struct invoked the `fmt_index` method defined on the `DatabaseOps` trait:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/src/plumbing.rs#L43-L48

which was auto-generated by the salsa macros:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-macros/src/database_storage.rs#L122-L126

### New code

The `DatabaseOps` trait no longer exists etc etc etc, so the approach looks different. Our goal is to fill in the `DebugWithDb` impl for `DependencyKeyIndex`:

XXX (I have to land my branch, I realize!)

I think the new way to do this would be to extend the `Ingredient` trait:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022/src/ingredient.rs#L7-L13

we should add a new `fmt_index` method there with a very similar signature. I changed the `index` to `Option<salsa::Id>` though.

```rust
    fn fmt_index(
        &self,
        index: Option<salsa::Id>,
        fmt: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result;
```

This will then force you to go and implement this method for all the various ingredients. One thing I think we will find is that we need to add a bit more information to do it -- for example, each one probably needs to take a `&'static str` with the right name. Let's walk through one of those. `FunctionIngredient` is used for tracked functions but also fields and things:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022/src/function.rs#L30

we would extend the struct with a `debug_name: &'static str` field and then modify the `new` method to take it as a second argument:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022/src/function.rs#L86

Finally we extend the various proc-macros that create functions to supply one. Sometimes, that's easy, like `#[tracked]` when applied to a function:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022-macros/src/tracked_fn.rs#L243

Just add something like 

```rust
let name = Literal::from(item_fn.ident); // get the name of the function as a string literal
```

and then

```rust
salsa::function::FunctionIngredient::new(index, #name)
```

(For other functions, like fields, you can use the name of the "config struct" that is already being generated.)

Anyway, once that compiles, you need to "connect" it to the `DebugWithDb` impl we saw earlier. To do THAT, we need to (a) extend the `HasJarsDyn` trait with the same `fmt_index` method we added to ingredient, except it should take a `DependencyKeyIndex` instead of an `Option<salsa::Id>`:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022/src/storage.rs#L155-L164

you will then have to add the method to impl for `HasJarsDyn` generated by `#[salsa::db`]:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022-macros/src/db.rs#L114

it will look very similar to the other methods, like this one:

https://github.com/salsa-rs/salsa/blob/9ff6fb3376527297dacbc9de4081a28373bebab0/components/salsa-2022-macros/src/db.rs#L136-L142

i.e., invoke `self.storage.ingredient`, which returns a `dyn Ingredient`, and then invoke the new method you added to that trait. 

Then as the final step you can call `HasJarsDyn::fmt_index` from the `DebugWithDb` impl.

**Comment by LuisCardosoOliveira** [comment]
Hi there!

Thanks for the excellent description @nikomatsakis.

Can I take this issue?

**Comment by nikomatsakis** [comment]
@LuisCardosoOliveira please! No need to ask permission. I think this issue is actually fairly high priority, it's a big usability challenge.

**Comment by nikomatsakis** [comment]
(Looks like @zjp-CN is taking it on)
