### ISSUE TITLE
Error message for wrong creation of tracked structs are misleading

### ISSUE THREAD

**Issue by kdy1** [salsa-rs/salsa#441]
Hi. I'm the author of [the stc project](https://github.com/dudykr/stc), and I'm evaluating salsa-2022.

As salsa database does not implement `Send` (or `Sync`, not sure), I used a dedicated thread for salsa-related operations.
But salsa fails with an assertion failure.

# Steps to reproduce:

1. Checkout this branch.

 - `git clone git@github.com:kdy1/stc.git -b salsa-assertion`

2. Run LSP using vscode.

You can press `F5` and it will launch extension development window.

3. Take a look at Output => `stc LS server`

x-ref: https://github.com/dudykr/stc/pull/999
This PR exists to prevent me from deleting the branch by mistake

**Comment by DropDemBits** [comment]
Looking into it:

- This assert only triggers if a tracked struct is trying to be created outside of a tracked function
- Looking at the backtrace, a `TypeCheckInput` is trying to be created inside of `stc_ts_lang_server::type_checker::prepare_input`, but it's not marked as a tracked function
- Marking it as a tracked function means that you can no longer take in a `&Arc<FileName>`, but since `prepare_input` converts it into a `SourceFile` anyway, you could probably take a `SourceFile` in directly

It'd probably be best for us to add an assert message clarifying that this kind of situation is happening though.

(I also had to change `watch-lsp` to `watch-lsp-client` in the vscode tasks file, but I'll open a PR for that 😄)

**Comment by kdy1** [comment]
Thank you! I didn't notice the cause. I'll change the title.
