### ISSUE TITLE
Freezing revision for several consequitive queries

### ISSUE THREAD

**Issue by matklad** [salsa-rs/salsa#53]
Currently, we track that revision is frozen while a single query is in progress, but we don't have a way to freeze the revision for consecutive queries. I think this might be important for correctness for clients which issue multiple queries for a single high-level op.

For example, IDE might ask for types (one query) and control flow info (other query) for syntax highlighting. If a revision bump happens in-between, the end result might be an inconsistent highlighting. 

One way to solve this is to turn "highlighting" itself into a query.

Another way is to place onus on consumers to check that revision haven't advanced before merging results of the consecutive queries.

The third way is to provide some explicit API for freezing revisions. This could work with a drop-guard style API, and means turning [this dynamic choice](https://github.com/salsa-rs/salsa/blob/a128861a2cdf28145e1dd365dac408d76f34b6b6/src/runtime.rs#L97-L99) of `None` vs `Some` into a static one.

**Comment by nikomatsakis** [comment]
I was expecting that such clients would define a "meta query", like this:

> One way to solve this is to turn "highlighting" itself into a query.

but it would be fairly simple to define something like `db.freeze_revision(|| ...)` that makes an "ad-hoc query". It would basically just acquire the lock, I imagine, and then invoke the closure. (This would also set the "query-in-progress" flag, which seems fine.

**Comment by matklad** [comment]
>I was expecting that such clients would define a "meta query", like this:

That might, or might not be the best solution. Drawbacks:

* you have to expose salsa at the API layer, you can't make it an impl detail of low-level compiler library
* defining a query is significantly more work then just writing functions.

**Comment by nikomatsakis** [comment]
Yes. `db.freeze_revision` seems ok.

**Comment by nikomatsakis** [comment]
So, I was considering just exposing the existing `freeze_revision` (which returns an RAII object). This seems like it would be maximally convenient for callers (RAII is nice) but I realized that there is an opportunity for people to screw things up. For example, they could somehow get the revision lock:

```rust
let lock = db.freeze_revision();
```

start executing a query and then drop it in the middle of that query. This would be bad because -- since the query observes that the lock is held on start, it won't try to acquire the lock, which would mean that things could get out of sync. So maybe the closure variant is better.

OTOH, there are lots of ways to mess up incremental (e.g., shared mutable state) and there's not a *memory safety* guarantee at play here. So maybe it suffices to just add a **warning** to the docs saying "do not release this lock in the middle of a query"?

**Comment by matklad** [comment]
>This would be bad because -- since the query observes that the lock is held on start, it won't try to acquire the lock, which would mean that things could get out of sync. 

Is this really the case with the current implementation? `RevisionGuard` does not set `query_in_progress`, so we have two different locks.
