### ISSUE TITLE
Potential livelock in freeze revision

### ISSUE THREAD

**Issue by matklad** [salsa-rs/salsa#61]
Current implementation of freeze revision is susceptible to a live-lock:

If one thread tries to advance the revision, and n other threads continuously execute queries, then the revision might never be incremented. 

To fix this, I think we'll need to block in `freeze_revision` if `pending_revision_increments` is greater then zero. Not sure what's the best way to do that, though? Something like this could work I guess?

```rust
while shared_state
          .pending_revision_increments
          .get(SeqCst) > 0 {
    let _ = self.shared_state.query_lock.upgradable_read();
}
```

I also wonder if `pending_revision_increments` duplicates some internal state of the `shared_state.query_lock`: it is essentially the number of blocked threads, so perhaps there's an API to get that?

https://github.com/salsa-rs/salsa/blob/fd2d1fbe2335f424b6525343b2e508302d3b83a4/src/runtime.rs#L103-L114

**Comment by nikomatsakis** [comment]
> If one thread tries to advance the revision, and n other threads continuously execute queries, then the revision might never be incremented.

Are you suggesting that this is due to lock starvation, or do something where the user is writing a big long loop while holding the query-lock?

If the former, I think parking-lot doesn't suffer from this problem.

If the latter, I feel like "don't do that" is a reasonable response, but I haven't had time to read the rest of your comment yet, so maybe it will change my opinion (i.e., I expect people to be checking for cancellation on a regular basis, and tuning this to deal with "jaggy" problems, and I'm not sure how much better we can do).

**Comment by matklad** [comment]
The latter, yeah. Thinking about it more, it looks like users indeed should just check for cancelation themselves. I think I am wrong about *never* bit as well: at worst, all queries will be freshened, which is a bounded amount of work. OTOH, it may make sense to check for pending increments in lock revision?

**Comment by matklad** [comment]
To expand on this, the core issue is that initiating a query while there are pending updates seems like an error, but we don’t detect/signal this in any way.

**Comment by nikomatsakis** [comment]
From the parking-lot docs:
 
> This rwlock uses eventual fairness to ensure that the lock will be fair on average without sacrificing performance. This is done by forcing a fair unlock on average every 0.5ms, which will force the lock to go to the next thread waiting for the rwlock.
>
> ...
> 
> You can also force a fair unlock by calling RwLockReadGuard::unlock_fair or RwLockWriteGuard::unlock_fair when unlocking a mutex instead of simply dropping the guard.

Perhaps, in the case of the query lock, we should simply always use "fair unlocks"? We don't expect a lot of contention on this lock I don't think. That would help ensure that the `set` gets processed in due time.

I could also imagine changing `lock_revision` so that it returns a `Result<RevisionGuard, PendingCancellation>` or something like that.

**Comment by nikomatsakis** [comment]
Fixed now.
