### ISSUE TITLE
some way to specify initial or default value for an input query

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#87]
Right now, input queries have no way to specify their *initial value* (value at revision zero).

It would be useful to be able to supply a function to do so. One case where I have found this to be true is if you have a query `all_files() -> Set` that returns the set of "all" your inputs -- it should start out returning the empty set.

In the general case, this feature interacts with the desire to support a `remove` on queries, because we need an extra bit of state now to distinguish whether a query was removed, so that we can accurately reflect when the value of the query changed (otherwise, `remove` can simply remove the key, since any attempt to access a removed key will panic). One option: don't support `remove` on queries that have an initial value -- for my query `all_files` above, removing doesn't really make any sense anyway.

**Comment by matklad** [comment]
>It would be useful to be able to supply a function to do so. One case where I have found this to be true is if you have a query all_files() -> Set that returns the set of "all" your inputs -- it should start out returning the empty set.

There's a simple way to fix that: in the `Default` impl for your database, just set all the relevant queries:

https://github.com/rust-analyzer/rust-analyzer/blob/f29b0172fbcbc88160980c2e7359f92d7c0d885d/crates/ra_analysis/src/db.rs#L29-L42

I think this covers `unit` queries perfectly. I am not sure what's the best way to handle query with inputs. One thing I wanted is to iterate the set of currently defined keys: `db.query(FileText).key_set()`. Currently I handle this by having a separate query which remebers a set of inputs.

**Comment by Marwes** [comment]
This would probably solve the first blocker I encountered in [gluon](https://github.com/gluon-lang/gluon). I modeled each module/source file as an input query but I don't have a way (or want to) specify all modules up front but instead just let the `db.source_file(module)` do a lookup for the file if it does not exist.

But, writing that makes me think that the "input query" might depend on other queries as well (say `source_root`) so maybe that is not the correct solution after all (maybe non-input queries could support `set` somehow?).

**Comment by matklad** [comment]
@Marwes I think that is possible if you don't make the query an input query? 

```
fn read_file(db: &impl MyDb, path: PathBuf) -> Option<String> {
   fs::read_to_string(&path).ok()
}
```

should "just work". This will be a query with zero-inputs, so it will be executed only once. To force it's re execution in every revision, you can mark it as volatile. Alternatively, you can have an input "fs_state() -> usize" query, and make `read_file` depend on that. Setting `fs_state` would cause all `read_file` queries to be re-executed. Invalidating individual files seems trickier, but should also be possible: on ca have a `fs_state() -> HashMap<PathBuf, usize>` input query, initially empty. After each "compilation", you can collect the set of files actually used and add them to the map at `0` version. 

In rust-analyzer I've done the opposite and just forced the problem to be such that I know all the inputs up-front, to avoid IO during computations and to have a single place to deal with file-system quirks. More about it [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/guide.md#source-roots-aka-filesystems-are-horrible)

**Comment by Marwes** [comment]
@matklad That seems like it would work, thanks! I had thought as far as to have some dummy `fn fs_state() -> usize` input to invalidate the file query but didn't see a way to only invalidate a specific file so I figured it was a dead end.

> In rust-analyzer I've done the opposite and just forced the problem to be such that I know all the inputs up-front, to avoid IO during computations and to have a single place to deal with file-system quirks. More about it here

Yeah, I looked to see what rust-analyser does in this case since I remembered that rust has the same issue with `#[path = .. ]` attributes. If I understand it correctly you do one pass through the source root to collect all files and then populate the input query with those files. Then the input files can be updated as changes happen?

 I think that works well for language servers and well ehough for compiling an entire project. With scripting I think it falls apart slightly since a compilation may only need to touch a subset of all the files in a source root (borrowing the terminology). Given that the compilation time of the script can be a large factor of the overall runtime of the script I want to only touch the files that actually matter for the script that is compiled.

**Comment by matklad** [comment]
Yeah, that’s how the analyzer works, and I agree that this won’t be a good fir for scripting. Hash map with versions should work, as long as you can have a “files involved in the compilation” query and some logic to ensure no updates are lost between the moment you read the file for the first time, and the moment you start wathcing it.

**Comment by bjorn3** [comment]
> some logic to ensure no updates are lost between the moment you read the file for the first time, and the moment you start wathcing it.

Watch first, then read?

**Comment by 1tgr** [comment]
I think the lack of default values for inputs is my number 1 niggle with Salsa[1]. Initialising everything in `impl Defautl for MyDatabase` works to an extent, but gets hard to manage as the number of inputs grows.

My suggestion:
1. Inputs are assumed to be `Default`
2. We have `#[salsa::input(default_with = default_fn)]` for those that are not
3. Inputs that have no default can be `Option` and callers can panic via `.unwrap()`
4. We could have a flag on `#[salsa::input]` that keeps the current panic behaviour if needed

_[1] the other two are the fact that I can't easily memoise a query that returns `f64`, and that query values have to be `fmt::Debug`._

**Comment by ryo33** [comment]
In my case, the default feature is really needed because of high dynamicity. In order to prevent panic i need to call set_* for every possible input (but this would be calls of universe eg all UUID).
Also I needs the remove feature because it's important to show whether value is available or not.

I prefer opt-in `#[salsa_input(default)]`.

**Comment by ryo33** [comment]
Does salsa 2022 support initial or default value?
