### ISSUE TITLE
poison database handles on panics

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#88]
Continuing the conversation with @kleimkuhler from https://github.com/salsa-rs/salsa/pull/81, I think we should **not** attempt to make an individual database handle panic safe, but we should instead **poision** the handles so that -- if they are used again -- you get an immediate panic. You can still recover from panics by using snapshots.

What I wrote in #81 was as follows: 

> It seems "ok" to say that we recover from panics at the level of snapshots but not within a thread. In fact, this makes some sense -- if the thread with the mutable handle panics, we don't know if all of the input queries etc are in a coherent state.
> 
> For example, you might be doing:
> 
> ```rust
> db.query_mut(Input1).set(...);
> let old_value = db.bar(); // read bar query, which panics unexpectedly
> db.query_mut(Input2).set(...); // this will never execute!
> ```
> 
> However, if we are not going to recover from panics -- and I am now thinking we should not -- then perhaps we want to at least _poison_ the database so we "fail fast". The idea would be to have some panic-guard that sets a "poisoned" flag in the runtime to true when unwinding, and any attempt to use that database handle again will panic quickly with "poisoned".

**Comment by kleimkuhler** [comment]
Based off my initial implementation of the panic guard, using `set` with a poisoned database handle will not panic because the handle is poisoned; it will panic because the `query_stack` is not empty [here](https://github.com/salsa-rs/salsa/blob/master/src/runtime.rs#L195)

We _could_ check if the handle is poisoned as well, but we would panic either way. I think if we want to distinguish the reason we are panicking, the option is there, but I don't think we can short circuit a query execution any earlier with this in mind.

**Comment by nikomatsakis** [comment]
Actually, we've decided to make the database handles *recover* from panics, as part of our cancellation mechanism (and, afaik, they currently do). See https://github.com/salsa-rs/salsa/pull/114
