### ISSUE TITLE
Support "none" storage

### ISSUE THREAD

**Issue by matklad** [salsa-rs/salsa#90]
It would be useful to support `none` storage variation, which bypasses all the salsa machinery, both value and dependecy storage. "None" queries should also not be present directly in the dep-graphs. 

A call to a none-query should work exactly like a function call. Why not make it a function call? To make an API nicer and to make it easier to change you mind later and elevate the function to a query (or, vice-verse, to downgrade query to a function).

Ideally `none` queries should allow not to define the query struct at all: basically, they are a sugar for adding arbitrary methods to the query group trait.

**Comment by cormacrelf** [comment]
The main reason I would want this would be to get orchestrated mutations for free in testing databases, especially in query groups that sit in a different crate from the `salsa::database`. But mutations can never be real queries anyway. Subtraits are just as non-ergonomic (require trait in scope) as query groups, so they work fine for this purpose. Not quite there on "later ... elevate ... to a query" because it does require some call site adjustment, but at least `cargo fix` can remove unused trait imports right?


```rust
trait Extensions: MyQueryGroup {
    fn ext_query(&self, key: K) -> V {
        // default impl
    }
    fn ext_mutation(&mut self, input: Whatever) {
        self.set_whatever(input, 5000);
        // ...
    }
}
```

**Comment by matklad** [comment]
Hm, this actually was implemented a while ago, se #salsa::transparent attribute
